
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/common/header/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { saveUserToDB } from "@/server/actions/user.action";
import { currentUser } from "@clerk/nextjs/server";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { AppSidebar } from "@/components/common/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ReduxProvider } from "@/store/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();

  if (user) {
    await saveUserToDB(user);
  }
  return (
    
      <html lang="en" suppressHydrationWarning>
        <ClerkProvider>
         
         
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased  `}
        >
           <ReduxProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider>
              <div
                style={{
                  color: "var(--text-color)",
                  backgroundColor: "var(--bg-color)",
                }}
                className="flex min-h-screen w-full "
              >
                <AppSidebar />
                <div className="flex-1 flex flex-col h-full relative ">
                   <Navbar />
                  <main className="flex-1  w-full h-full ">
                     
                    {children}
                    </main>
                </div>
              </div>
            </SidebarProvider>
          </ThemeProvider>
          </ReduxProvider>
        </body>
        
       
           </ClerkProvider>
      </html>
 
  );
}
